apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finaltodoapp
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: todoapp=georgeao/finaltodoapp
    argocd-image-updater.argoproj.io/yourtool.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/george-ajayiola/todolist-app.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
