apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-test-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: georgeao/finaltodoapp
    argocd-image-updater.argoproj.io/todoapp.update-strategy: digest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/george-ajayiola/todolist-app.git
    targetRevision: HEAD
    path: kubernetes
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
